#!/usr/bin/env python3
"""
flow_parser.py — Network Traffic Flow Aggregator using TShark
--------------------------------------------------------------
Processes .pcap files or live captures into bidirectional flow-level records.
Streams packets via TShark subprocess — never loads entire pcap into memory.

Flows are sent in real-time to a remote HTTP API endpoint via POST requests.
The script is designed to run as a persistent background service (systemd).

Output fields match the schema shown below (Zeek/CTU-13 inspired):
    src_ip, dst_ip, src_port, dst_port, proto, service, conn_state,
    duration, src_bytes, dst_bytes, missed_bytes,
    src_pkts, src_ip_bytes, dst_pkts, dst_ip_bytes,
    dns_qclass, dns_qtype, dns_rcode,<
    http_trans_depth, http_request_body_len, http_response_body_len,
    http_status_code, raw_log

Usage:
    # From pcap file → send to API
    python flow_parser.py -f capture.pcap --server http://0.0.0.0:8000/analyse

    # Live capture → send to API with 2-min idle timeout + local JSON backup
    python flow_parser.py -i eth0 --server http://192.168.1.100:8000/analyse --timeout 120 -o flows.json

    # Live capture → default API endpoint
    python flow_parser.py -i eth0

    # Run as daemon (background process, survives terminal close)
    python flow_parser.py -i eth0 --daemon

Author: Generated by Claude
"""

import argparse
import csv
import json
import os
import signal
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from queue import Empty, Queue
from typing import Dict, Iterator, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_API_ENDPOINT = "http://127.0.0.1:8000/api/analyze"

SERVICE_MAP: Dict[int, str] = {
    20:    "ftp-data",
    21:    "ftp",
    22:    "ssh",
    23:    "telnet",
    25:    "smtp",
    53:    "dns",
    67:    "dhcp",
    68:    "dhcp",
    80:    "http",
    110:   "pop3",
    123:   "ntp",
    143:   "imap",
    161:   "snmp",
    162:   "snmp",
    179:   "bgp",
    443:   "ssl",
    465:   "smtp",
    514:   "syslog",
    587:   "smtp",
    636:   "ssl",
    993:   "imap",
    995:   "pop3",
    1194:  "openvpn",
    1433:  "mssql",
    1521:  "oracle",
    3306:  "mysql",
    3389:  "rdp",
    5432:  "postgresql",
    5601:  "kibana",
    6379:  "redis",
    6443:  "ssl",
    8080:  "http",
    8443:  "ssl",
    9200:  "elasticsearch",
    27017: "mongodb",
}

# TCP flag bit masks
TCP_FIN = 0x01
TCP_SYN = 0x02
TCP_RST = 0x04
TCP_PSH = 0x08
TCP_ACK = 0x10
TCP_URG = 0x20

TSHARK_FIELDS = [
    "frame.time_epoch",
    "ip.src",
    "ip.dst",
    "tcp.srcport",
    "tcp.dstport",
    "udp.srcport",
    "udp.dstport",
    "ip.proto",
    "frame.len",
    "tcp.flags",
    "ip.len",
    "dns.qry.class",
    "dns.qry.type",
    "dns.flags.rcode",
    "http.request.version",
    "http.content_length",
    "http.response",          # 16 — 1 if this packet is an HTTP response
    "http.response.code",
]

TSHARK_SEPARATOR = "|"

# Retry / queue settings
RECONNECT_DELAY  = 5      # seconds between retries
SEND_TIMEOUT     = 10     # HTTP request timeout in seconds
MAX_QUEUE_SIZE   = 10_000 # max buffered flows in memory
BATCH_SIZE       = 50     # number of flows to POST in one request
BATCH_TIMEOUT    = 2.0    # seconds to wait before sending a partial batch

# PID file for daemon mode
PID_FILE = "/tmp/flow_parser.pid"


# ---------------------------------------------------------------------------
# Zeek-style connection state codes
# ---------------------------------------------------------------------------

def derive_conn_state(
    saw_syn: bool,
    saw_synack: bool,
    saw_fin_orig: bool,
    saw_fin_resp: bool,
    saw_rst: bool,
    saw_data: bool,
    rst_from_orig: bool,
    protocol: str,
) -> str:
    if protocol != "tcp":
        return "-"
    if saw_rst:
        if not saw_synack:
            return "RSTOS0" if rst_from_orig else "REJ"
        return "RSTO" if rst_from_orig else "RSTR"
    if saw_syn and not saw_synack:
        return "S0"
    if saw_syn and saw_synack and not saw_data and not saw_fin_orig and not saw_fin_resp:
        return "S1"
    if saw_synack and saw_fin_orig and not saw_fin_resp:
        return "S2"
    if saw_synack and saw_fin_resp and not saw_fin_orig:
        return "S3"
    if saw_synack and saw_fin_orig and saw_fin_resp:
        return "SF"
    if not saw_syn and saw_data:
        return "OTH"
    return "OTH"


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

FlowKey = Tuple[str, str, int, int, str]


@dataclass
class FlowRecord:
    src_ip:   str
    dst_ip:   str
    src_port: int
    dst_port: int
    proto:    str

    service:  str = "-"

    first_seen: float = 0.0
    last_seen:  float = 0.0
    duration:   float = 0.0

    src_pkts:     int = 0
    src_bytes:    int = 0
    src_ip_bytes: int = 0
    dst_pkts:     int = 0
    dst_bytes:    int = 0
    dst_ip_bytes: int = 0
    missed_bytes: int = 0

    conn_state: str = "-"

    dns_qclass: int = 0
    dns_qtype:  int = 0
    dns_rcode:  int = 0

    http_trans_depth:        int = 0
    http_request_body_len:   int = 0
    http_response_body_len:  int = 0
    http_status_code:        int = 0

    raw_log: None = None

    _saw_syn:       bool = field(default=False, repr=False)
    _saw_synack:    bool = field(default=False, repr=False)
    _saw_fin_orig:  bool = field(default=False, repr=False)
    _saw_fin_resp:  bool = field(default=False, repr=False)
    _saw_rst:       bool = field(default=False, repr=False)
    _saw_data:      bool = field(default=False, repr=False)
    _rst_from_orig: bool = field(default=False, repr=False)

    def finalize(self) -> None:
        self.duration   = round(self.last_seen - self.first_seen, 6)
        self.conn_state = derive_conn_state(
            saw_syn       = self._saw_syn,
            saw_synack    = self._saw_synack,
            saw_fin_orig  = self._saw_fin_orig,
            saw_fin_resp  = self._saw_fin_resp,
            saw_rst       = self._saw_rst,
            saw_data      = self._saw_data,
            rst_from_orig = self._rst_from_orig,
            protocol      = self.proto,
        )

    def to_dict(self) -> dict:
        self.finalize()
        return {
            "src_ip":                   self.src_ip,
            "dst_ip":                   self.dst_ip,
            "src_port":                 self.src_port,
            "dst_port":                 self.dst_port,
            "proto":                    self.proto,
            "service":                  self.service,
            "conn_state":               self.conn_state,
            "duration":                 round(self.duration, 6),
            "src_bytes":                self.src_bytes,
            "dst_bytes":                self.dst_bytes,
            "missed_bytes":             self.missed_bytes,
            "src_pkts":                 self.src_pkts,
            "src_ip_bytes":             self.src_ip_bytes,
            "dst_pkts":                 self.dst_pkts,
            "dst_ip_bytes":             self.dst_ip_bytes,
            "dns_qclass":               self.dns_qclass,
            "dns_qtype":                self.dns_qtype,
            "dns_rcode":                self.dns_rcode,
            "http_trans_depth":         self.http_trans_depth,
            "http_request_body_len":    self.http_request_body_len,
            "http_response_body_len":   self.http_response_body_len,
            "http_status_code":         self.http_status_code,
            "raw_log":                  self.raw_log,
            "timestamp":                self.first_seen,
        }


# ---------------------------------------------------------------------------
# TShark helpers
# ---------------------------------------------------------------------------

def build_tshark_command(
    source: str,
    is_interface: bool = False,
    capture_filter: str = "",
    display_filter: str = "ip",
) -> List[str]:
    cmd = ["tshark"]
    if is_interface:
        cmd += ["-i", source]
        if capture_filter:
            cmd += ["-f", capture_filter]
    else:
        cmd += ["-r", source]
    if display_filter:
        cmd += ["-Y", display_filter]
    cmd += ["-T", "fields"]
    for f in TSHARK_FIELDS:
        cmd += ["-e", f]
    cmd += [
        "-E", f"separator={TSHARK_SEPARATOR}",
        "-E", "header=n",
        "-E", "occurrence=f",
        "-q",
    ]
    return cmd


def _int(val: str, default: int = 0) -> int:
    try:
        return int(val) if val else default
    except ValueError:
        return default


def parse_packet_line(line: str) -> Optional[dict]:
    parts = line.rstrip("\n").split(TSHARK_SEPARATOR)
    if len(parts) < len(TSHARK_FIELDS):
        return None

    (ts, ip_src, ip_dst,
     tcp_sport, tcp_dport,
     udp_sport, udp_dport,
     ip_proto, frame_len,
     tcp_flags_hex, ip_len,
     dns_qclass, dns_qtype, dns_rcode,
     http_req_ver, http_content_len, http_resp_num,
     http_status) = parts[:18]

    if not ip_src or not ip_dst:
        return None

    try:
        timestamp = float(ts)
        proto_num = _int(ip_proto)
        length    = _int(frame_len)
        ip_length = _int(ip_len)
    except ValueError:
        return None

    if proto_num == 6:
        protocol = "tcp"
        sport = _int(tcp_sport)
        dport = _int(tcp_dport)
    elif proto_num == 17:
        protocol = "udp"
        sport = _int(udp_sport)
        dport = _int(udp_dport)
    elif proto_num == 1:
        protocol = "icmp"
        sport = 0
        dport = 0
    else:
        protocol = f"proto{proto_num}"
        sport = 0
        dport = 0

    tcp_flags = 0
    if tcp_flags_hex:
        try:
            tcp_flags = int(tcp_flags_hex, 16)
        except ValueError:
            pass

    return {
        "timestamp":      timestamp,
        "ip_src":         ip_src,
        "ip_dst":         ip_dst,
        "sport":          sport,
        "dport":          dport,
        "protocol":       protocol,
        "frame_len":      length,
        "ip_len":         ip_length,
        "tcp_flags":      tcp_flags,
        "dns_qclass":     _int(dns_qclass),
        "dns_qtype":      _int(dns_qtype),
        "dns_rcode":      _int(dns_rcode),
        "http_req":       bool(http_req_ver),
        "http_req_body":  _int(http_content_len) if http_req_ver else 0,
        "http_resp_body": _int(http_content_len) if http_resp_num else 0,
        "http_status":    _int(http_status),
    }


def stream_packets(tshark_cmd: List[str]) -> Iterator[dict]:
    try:
        proc = subprocess.Popen(
            tshark_cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1,
        )
    except FileNotFoundError:
        print("ERROR: tshark not found. Install Wireshark/TShark first.", file=sys.stderr)
        sys.exit(1)

    try:
        for line in proc.stdout:
            pkt = parse_packet_line(line)
            if pkt:
                yield pkt
    finally:
        proc.stdout.close()
        proc.wait()
        if proc.returncode not in (0, None, -2):
            err = proc.stderr.read()
            if err:
                print(f"TShark stderr: {err[:500]}", file=sys.stderr)


# ---------------------------------------------------------------------------
# Service inference & TCP flags
# ---------------------------------------------------------------------------

def infer_service(sport: int, dport: int, protocol: str) -> str:
    if protocol == "icmp":
        return "icmp"
    for port in [dport, sport]:
        if port in SERVICE_MAP:
            return SERVICE_MAP[port]
    return "-"


def update_tcp_flags(record: FlowRecord, flags: int, is_forward: bool) -> None:
    if flags & TCP_SYN and not (flags & TCP_ACK):
        record._saw_syn = True
    if flags & TCP_SYN and flags & TCP_ACK:
        record._saw_synack = True
    if flags & TCP_RST:
        record._saw_rst = True
        record._rst_from_orig = is_forward
    if flags & TCP_FIN:
        if is_forward:
            record._saw_fin_orig = True
        else:
            record._saw_fin_resp = True
    if (flags & TCP_PSH or flags & TCP_ACK) and not (flags & TCP_SYN):
        record._saw_data = True


# ---------------------------------------------------------------------------
# Flow table
# ---------------------------------------------------------------------------

def make_flow_key(
    ip_src: str, ip_dst: str,
    sport: int, dport: int,
    protocol: str,
) -> Tuple[FlowKey, bool]:
    a = (ip_src, sport)
    b = (ip_dst, dport)
    if a <= b:
        return (ip_src, ip_dst, sport, dport, protocol), True
    else:
        return (ip_dst, ip_src, dport, sport, protocol), False


class FlowTable:
    def __init__(self, idle_timeout: float = 0):
        self.flows:         Dict[FlowKey, FlowRecord] = {}
        self.idle_timeout:  float = idle_timeout
        self._last_cleanup: float = 0

    def process_packet(self, pkt: dict) -> List[FlowRecord]:
        key, is_forward = make_flow_key(
            pkt["ip_src"], pkt["ip_dst"],
            pkt["sport"],  pkt["dport"],
            pkt["protocol"],
        )
        ts        = pkt["timestamp"]
        frame_len = pkt["frame_len"]
        ip_len    = pkt["ip_len"]

        if key not in self.flows:
            ip_a, ip_b, port_a, port_b, proto = key
            self.flows[key] = FlowRecord(
                src_ip     = ip_a,
                dst_ip     = ip_b,
                src_port   = port_a,
                dst_port   = port_b,
                proto      = proto,
                service    = infer_service(port_a, port_b, proto),
                first_seen = ts,
                last_seen  = ts,
            )

        rec = self.flows[key]
        rec.last_seen = max(rec.last_seen, ts)

        if is_forward:
            rec.src_pkts     += 1
            rec.src_bytes    += frame_len
            rec.src_ip_bytes += ip_len
        else:
            rec.dst_pkts     += 1
            rec.dst_bytes    += frame_len
            rec.dst_ip_bytes += ip_len

        if pkt["protocol"] == "tcp":
            update_tcp_flags(rec, pkt["tcp_flags"], is_forward)

        if pkt["dns_qclass"] and not rec.dns_qclass:
            rec.dns_qclass = pkt["dns_qclass"]
        if pkt["dns_qtype"] and not rec.dns_qtype:
            rec.dns_qtype = pkt["dns_qtype"]
        if pkt["dns_rcode"] and not rec.dns_rcode:
            rec.dns_rcode = pkt["dns_rcode"]

        if pkt["http_req"]:
            rec.http_trans_depth += 1
        if pkt["http_req_body"]:
            rec.http_request_body_len += pkt["http_req_body"]
        if pkt["http_resp_body"]:
            rec.http_response_body_len += pkt["http_resp_body"]
        if pkt["http_status"] and not rec.http_status_code:
            rec.http_status_code = pkt["http_status"]

        expired = []
        if self.idle_timeout > 0 and (ts - self._last_cleanup) > 10:
            self._last_cleanup = ts
            expired = list(self._expire_flows(ts))

        return expired

    def _expire_flows(self, current_ts: float) -> Iterator[FlowRecord]:
        expired_keys = [
            k for k, v in self.flows.items()
            if (current_ts - v.last_seen) >= self.idle_timeout
        ]
        for k in expired_keys:
            yield self.flows.pop(k)

    def all_flows(self) -> Iterator[FlowRecord]:
        yield from self.flows.values()


# ---------------------------------------------------------------------------
# HTTP API Sender
# ---------------------------------------------------------------------------

class ApiSender:
    """
    Background thread that batches flows from a queue and POSTs them
    to the configured HTTP API endpoint as JSON arrays.

    Retries indefinitely on failure — flows are re-queued so no data
    is lost if the server is temporarily unreachable.
    """

    def __init__(self, endpoint: str):
        self.endpoint    = endpoint
        self.queue:      Queue = Queue(maxsize=MAX_QUEUE_SIZE)
        self._thread     = threading.Thread(
                               target=self._run, daemon=True, name="ApiSender"
                           )
        self._stop       = threading.Event()
        self._sent:      int = 0
        self._dropped:   int = 0
        self._errors:    int = 0

    def start(self) -> None:
        self._thread.start()
        print(f"[*] API sender started → {self.endpoint}")

    def stop(self) -> None:
        self._stop.set()
        self._thread.join(timeout=15)
        print(f"[*] API sender stopped. Sent: {self._sent} | "
              f"Dropped: {self._dropped} | Errors: {self._errors}")

    def send(self, flow: FlowRecord) -> None:
        try:
            self.queue.put_nowait(flow.to_dict())
        except Exception:
            self._dropped += 1

    def _post(self, batch: List[dict]) -> bool:
        """POST a batch of flow dicts to the API. Returns True on success."""
        payload = json.dumps(batch).encode("utf-8")
        req = urllib.request.Request(
            self.endpoint,
            data    = payload,
            headers = {
                "Content-Type": "application/json",
                "User-Agent":   "flow-parser/1.0",
            },
            method = "POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=SEND_TIMEOUT) as resp:
                status = resp.getcode()
                if status in (200, 201, 202, 204):
                    self._sent += len(batch)
                    return True
                print(f"[!] API returned HTTP {status}", file=sys.stderr)
                self._errors += 1
                return False
        except urllib.error.URLError as e:
            print(f"[!] POST failed: {e.reason} — will retry in {RECONNECT_DELAY}s",
                  file=sys.stderr)
            self._errors += 1
            return False
        except Exception as e:
            print(f"[!] Unexpected send error: {e}", file=sys.stderr)
            self._errors += 1
            return False

    def _run(self) -> None:
        batch: List[dict] = []
        last_flush = time.time()

        while not self._stop.is_set():
            # Drain queue into batch
            try:
                item = self.queue.get(timeout=0.2)
                batch.append(item)
            except Empty:
                pass

            now = time.time()
            batch_ready = len(batch) >= BATCH_SIZE
            timeout_hit = batch and (now - last_flush) >= BATCH_TIMEOUT

            if batch and (batch_ready or timeout_hit):
                success = self._post(batch)
                if success:
                    batch = []
                    last_flush = now
                else:
                    # Re-queue the batch items for retry
                    for item in batch:
                        try:
                            self.queue.put_nowait(item)
                        except Exception:
                            self._dropped += 1
                    batch = []
                    self._stop.wait(timeout=RECONNECT_DELAY)

        # Drain remaining on shutdown
        if batch:
            self._post(batch)
        remaining = []
        while not self.queue.empty():
            try:
                remaining.append(self.queue.get_nowait())
            except Empty:
                break
        if remaining:
            self._post(remaining)


# ---------------------------------------------------------------------------
# Local output writers
# ---------------------------------------------------------------------------

CSV_COLUMNS = [
    "src_ip", "dst_ip", "src_port", "dst_port", "proto",
    "service", "conn_state", "duration",
    "src_bytes", "dst_bytes", "missed_bytes",
    "src_pkts", "src_ip_bytes",
    "dst_pkts", "dst_ip_bytes",
    "dns_qclass", "dns_qtype", "dns_rcode",
    "http_trans_depth", "http_request_body_len",
    "http_response_body_len", "http_status_code",
    "raw_log",
]


def write_json(flows: List[FlowRecord], path: str) -> None:
    records = [f.to_dict() for f in flows]
    with open(path, "w") as fh:
        json.dump(records, fh, indent=2)
    print(f"[+] Wrote {len(records)} flows → {path}")


def write_csv(flows: List[FlowRecord], path: str) -> None:
    with open(path, "w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=CSV_COLUMNS, extrasaction="ignore")
        writer.writeheader()
        for f in flows:
            writer.writerow(f.to_dict())
    print(f"[+] Wrote {len(flows)} flows → {path}")


# ---------------------------------------------------------------------------
# Daemon mode
# ---------------------------------------------------------------------------

def daemonize(log_file: str = "/tmp/flow_parser.log") -> None:
    """
    Fork into background. Redirects stdout/stderr to a log file.
    Writes PID to PID_FILE so the process can be stopped later.
    """
    # First fork
    try:
        pid = os.fork()
        if pid > 0:
            print(f"[*] Daemon started with PID {pid}. Logs → {log_file}")
            sys.exit(0)
    except OSError as e:
        print(f"Fork #1 failed: {e}", file=sys.stderr)
        sys.exit(1)

    os.setsid()

    # Second fork
    try:
        pid = os.fork()
        if pid > 0:
            sys.exit(0)
    except OSError as e:
        print(f"Fork #2 failed: {e}", file=sys.stderr)
        sys.exit(1)

    # Write PID
    with open(PID_FILE, "w") as f:
        f.write(str(os.getpid()))

    # Redirect stdin/stdout/stderr
    sys.stdout.flush()
    sys.stderr.flush()
    with open(os.devnull, "r") as devnull:
        os.dup2(devnull.fileno(), sys.stdin.fileno())
    log = open(log_file, "a")
    os.dup2(log.fileno(), sys.stdout.fileno())
    os.dup2(log.fileno(), sys.stderr.fileno())

    print(f"[*] Daemon process started at {time.strftime('%Y-%m-%d %H:%M:%S')}", flush=True)


def stop_daemon() -> None:
    """Stop a running daemon by PID file."""
    if not os.path.exists(PID_FILE):
        print("No PID file found — daemon may not be running.")
        return
    with open(PID_FILE) as f:
        pid = int(f.read().strip())
    try:
        os.kill(pid, signal.SIGTERM)
        print(f"[*] Sent SIGTERM to PID {pid}")
        os.remove(PID_FILE)
    except ProcessLookupError:
        print(f"Process {pid} not found — already stopped.")
        os.remove(PID_FILE)
    except PermissionError:
        print(f"Permission denied killing PID {pid}")


# ---------------------------------------------------------------------------
# Argument parser
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Parse network traffic into flow-level records and stream to an HTTP API.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Read pcap and POST flows to API
  python flow_parser.py -f capture.pcap

  # Live capture with custom server
  python flow_parser.py -i eth0 --server http://192.168.1.100:8000/analyse

  # Live capture as background daemon
  python flow_parser.py -i eth0 --daemon

  # Stop running daemon
  python flow_parser.py --stop

  # Install as systemd service (run as root)
  python flow_parser.py -i eth0 --install-service
        """
    )

    src = p.add_mutually_exclusive_group()
    src.add_argument("-f", "--file",      metavar="PCAP",  help="Input .pcap / .pcapng file")
    src.add_argument("-i", "--interface", metavar="IFACE", help="Live capture interface (e.g. eth0)")

    p.add_argument("--server",  metavar="URL",
                   default=DEFAULT_API_ENDPOINT,
                   help=f"API endpoint URL (default: {DEFAULT_API_ENDPOINT})")
    p.add_argument("-o", "--output", metavar="FILE", default=None,
                   help="Also save flows locally (.json or .csv)")
    p.add_argument("--format", choices=["json", "csv"], default=None)
    p.add_argument("--timeout", type=float, default=60, metavar="SECS",
                   help="Idle flow timeout in seconds (default: 60)")
    p.add_argument("--filter", default="ip", metavar="FILTER",
                   help='TShark display filter (default: "ip")')
    p.add_argument("--capture-filter", default="", metavar="BPF",
                   help="BPF capture filter for live mode")
    p.add_argument("--daemon", action="store_true",
                   help="Run as a background daemon process")
    p.add_argument("--log-file", default="/tmp/flow_parser.log", metavar="FILE",
                   help="Log file path when running as daemon")
    p.add_argument("--stop", action="store_true",
                   help="Stop a running daemon")
    p.add_argument("--install-service", action="store_true",
                   help="Print a systemd service unit and instructions")
    p.add_argument("--print-command", action="store_true")
    return p.parse_args()


def detect_format(output_path: Optional[str], fmt: Optional[str]) -> str:
    if fmt:
        return fmt
    if output_path and output_path.endswith(".csv"):
        return "csv"
    return "json"


def print_systemd_service(args: argparse.Namespace) -> None:
    script_path = os.path.abspath(__file__)
    iface = args.interface or "eth0"
    unit = f"""
# ─── flow_parser.service ────────────────────────────────────────────────────
# Install:
#   sudo cp flow_parser.service /etc/systemd/system/
#   sudo systemctl daemon-reload
#   sudo systemctl enable --now flow_parser
#   sudo systemctl status flow_parser
# ─────────────────────────────────────────────────────────────────────────────

[Unit]
Description=Flow Parser — real-time network flow exporter
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart={sys.executable} {script_path} -i {iface} --server {args.server} --timeout {args.timeout}
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
# Run as root so tshark can capture on raw sockets
User=root

[Install]
WantedBy=multi-user.target
"""
    print(unit)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    args = parse_args()

    if args.stop:
        stop_daemon()
        return

    if args.install_service:
        print_systemd_service(args)
        return

    if not args.file and not args.interface:
        print("ERROR: Specify -f FILE or -i INTERFACE (or --stop / --install-service).",
              file=sys.stderr)
        sys.exit(1)

    if args.daemon:
        daemonize(args.log_file)

    source   = args.file or args.interface
    is_iface = args.interface is not None

    out_format = detect_format(args.output, args.format)

    cmd = build_tshark_command(
        source         = source,
        is_interface   = is_iface,
        capture_filter = args.capture_filter,
        display_filter = args.filter,
    )

    if args.print_command:
        print("TShark command:\n  " + " \\\n    ".join(cmd))
        sys.exit(0)

    print(f"[*] Source       : {'interface ' if is_iface else ''}{source}", flush=True)
    print(f"[*] API endpoint : {args.server}", flush=True)
    if args.output:
        print(f"[*] Local output : {args.output} ({out_format.upper()})", flush=True)
    print(f"[*] Idle timeout : {args.timeout}s", flush=True)
    print(flush=True)

    sender = ApiSender(args.server)
    sender.start()

    table   = FlowTable(idle_timeout=args.timeout)
    count   = 0
    t_start = time.time()

    try:
        for pkt in stream_packets(cmd):
            expired = table.process_packet(pkt)
            for flow in expired:
                sender.send(flow)
            count += 1
            if count % 10_000 == 0:
                elapsed = time.time() - t_start
                print(f"  → {count:,} pkts | {len(table.flows):,} active flows | "
                      f"{elapsed:.1f}s | queue: {sender.queue.qsize()}", flush=True)
    except KeyboardInterrupt:
        print("\n[!] Interrupted by user.", flush=True)

    remaining = list(table.all_flows())
    elapsed   = time.time() - t_start
    print(f"[+] Done: {count:,} packets → {len(remaining):,} remaining flows in {elapsed:.2f}s",
          flush=True)

    for flow in remaining:
        sender.send(flow)

    print(f"[*] Flushing send queue ({sender.queue.qsize()} items)...", flush=True)
    deadline = time.time() + 20
    while not sender.queue.empty() and time.time() < deadline:
        time.sleep(0.2)
    sender.stop()

    if args.output:
        if out_format == "csv":
            write_csv(remaining, args.output)
        else:
            write_json(remaining, args.output)


if __name__ == "__main__":
    main()