import { useState } from "react";
import { Search, Sparkles, HelpCircle, ShieldCheck } from "lucide-react";
import FaqItem from "./FaqItem";

const FAQS = [
  {
    q: "How does the ML anomaly detection work?",
    a: "The system uses an XGBoost model trained on network traffic patterns. Each packet is scored in real time — if the confidence exceeds the threshold, the event is flagged as an anomaly and passed to the LLM for deeper analysis.",
  },
  {
    q: 'What does "needs manual review" mean?',
    a: "When the ML and LLM models disagree, or when confidence is below a safe threshold, the alert is flagged for a human analyst to review before any automated action is taken.",
  },
  {
    q: "How are suggestions generated?",
    a: "Suggestions are derived from open alerts grouped by attack type and source IP. The recommended action and evidence are generated by the LLM at analysis time and stored alongside each alert.",
  },
  {
    q: "What is final confidence?",
    a: "Final confidence is a weighted combination of the ML model confidence and the LLM confidence. It reflects the overall certainty of the system about the detected threat.",
  },
  {
    q: "How do I update an alert status?",
    a: "Open the alert detail from the Threats Analysis page, then use the action buttons at the bottom of the modal to mark it as resolved, ignored, or reviewed.",
  },
];

export default function FAQ() {
  const [search, setSearch] = useState("");

  const filtered = FAQS.filter(
    (f) =>
      f.q.toLowerCase().includes(search.toLowerCase()) ||
      f.a.toLowerCase().includes(search.toLowerCase()),
  );

  return (
    <div
      className="
        relative overflow-hidden
        rounded-3xl border border-slate-700/60
        bg-slate-900/70 backdrop-blur-xl
        light:bg-white/70 light:border-slate-200
        p-6
      "
    >
      {/* Glow */}
      <div className="absolute -top-16 right-0 w-52 h-52 bg-fuchsia-500/10 blur-3xl rounded-full" />
      <div className="absolute bottom-0 left-0 w-52 h-52 bg-cyan-500/10 blur-3xl rounded-full" />

      <div className="relative">
        {/* Header */}
        <div className="mb-6">
          <div className="flex items-center gap-2 mb-3 text-fuchsia-400 light:text-fuchsia-500">
            <Sparkles className="w-4 h-4" />
            <span className="uppercase tracking-[0.2em] text-[11px] font-semibold">
              Knowledge Base
            </span>
          </div>

          <div className="flex items-center gap-3 mb-3">
            <div
              className="
                w-12 h-12 rounded-2xl flex items-center justify-center
                bg-gradient-to-br from-cyan-500/20 to-cyan-700/10
                border border-cyan-500/20 text-cyan-300
                light:from-cyan-50 light:to-cyan-100/60
                light:border-cyan-200 light:text-cyan-600
              "
            >
              <HelpCircle className="w-6 h-6" />
            </div>

            <div>
              <h1 className="text-2xl md:text-3xl font-bold text-white light:text-slate-900">
                Frequently Asked Questions
              </h1>

              <p className="text-sm text-slate-400 light:text-slate-500 mt-1">
                Quick answers about alerts, ML analysis, anomaly detection, and
                response actions.
              </p>
            </div>
          </div>
        </div>

        {/* Search */}
        <div className="relative mb-6">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500 light:text-slate-400" />

          <input
            type="text"
            placeholder="Search for help..."
            className="
              w-full h-12 rounded-2xl border pl-12 pr-4
              text-sm outline-none transition-all
              border-slate-700 bg-slate-800/70 text-white placeholder:text-slate-500
              focus:border-fuchsia-500 focus:ring-2 focus:ring-fuchsia-500/20
              light:border-slate-200 light:bg-white/80 light:text-slate-800
              light:placeholder:text-slate-400
              light:focus:border-fuchsia-400 light:focus:ring-fuchsia-400/20
            "
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>

        {/* FAQ List */}
        <div className="space-y-4">
          {filtered.length ? (
            filtered.map((f, i) => (
              <div
                key={i}
                className="
                  rounded-2xl border border-slate-700/60
                  bg-slate-800/40
                  hover:border-slate-600
                  light:border-slate-200 light:bg-slate-50/60
                  light:hover:border-slate-300
                  transition-all duration-300
                "
              >
                <FaqItem q={f.q} a={f.a} />
              </div>
            ))
          ) : (
            <div
              className="
                flex flex-col items-center justify-center
                text-center py-10 rounded-2xl
                border border-dashed border-slate-700
                bg-slate-800/30
                light:border-slate-300 light:bg-slate-50/40
              "
            >
              <div
                className="
                  w-14 h-14 rounded-2xl flex items-center justify-center
                  bg-slate-800 border border-slate-700
                  light:bg-slate-100 light:border-slate-200
                  mb-4
                "
              >
                <ShieldCheck className="w-6 h-6 text-slate-400 light:text-slate-500" />
              </div>

              <h3 className="text-white light:text-slate-800 font-semibold mb-2">
                No matching results
              </h3>

              <p className="text-sm text-slate-500 light:text-slate-400">
                No FAQ found for{" "}
                <span className="text-slate-300 light:text-slate-700 font-medium">
                  "{search}"
                </span>
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
